inher it_from:
  - .rubocop_airbnb.yml
  - .rubocop_todo.yml
# rubocopを使いたくないファイル
AllCops:
  - 'db/**/*'
  - 'bin/*'
  - 'config/environments/*'
  - 'config/application.rb'
  - 'config/initializers/*'
  - 'config/spring.rb'
  - 'lib/tasks/*'
  - 'vendor/**/*'
  - 'path/ruby'